# HW-12 CODEOWNERS test
name: Hello CI

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print messages
        run: |
          echo "Hello from CI!"
          date
          echo "Commit Hash: ${{ github.sha }}"
